spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:h2:tcp://localhost/~/insshop
    username: sa
  thymeleaf:
    prefix: classpath:templates/
    suffix: .html
    mode: HTML
    check-template-location: true
    cache: false
  config:
    activate:
      on-profile: test
  # 실 운영서버에서는 주의
  devtools:
    remote:
      restart:
        enabled: false
    livereload:
      enabled: true
  sql:
    init:
      schema-locations: classpath*:sql/schema.sql
      mode: always
